New-Mailbox -Room -Name "BSRM04" -DisplayName "BSRM04" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName BESTSPA-Room4@best-spa.com
New-Mailbox -Room -Name "BSRM06" -DisplayName "BSRM06" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName BESTSPA-Room6@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Room 5" -DisplayName "BEST SPA - Room 5" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName BESTSPA-Room5@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Cirrus" -DisplayName "BEST SPA - Cirrus" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Cirrus@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Dado" -DisplayName "BEST SPA - Dado" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Dado@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Ghost" -DisplayName "BEST SPA - Ghost" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Ghost@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Mars" -DisplayName "BEST SPA - Mars" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Mars@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Moon" -DisplayName "BEST SPA - Moon" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Moon@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Saturn" -DisplayName "BEST SPA - Saturn" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Saturn@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Showroom" -DisplayName "BEST SPA - Showroom" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Showroom@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Smooth" -DisplayName "BEST SPA - Smooth" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Smooth@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Venus" -DisplayName "BEST SPA - Venus" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Venus@best-spa.com
New-Mailbox -Room -Name "BEST SPA - Vertigo" -DisplayName "BEST SPA - Vertigo" -OrganizationalUnit "OU=Resources,OU=Cerreto D'Esi,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Vertigo@best-spa.com
New-Mailbox -Room -Name "HTF-Boardroom" -DisplayName "HTF-Boardroom" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName HFTTRT@broan.com
New-Mailbox -Room -Name "room.plant.meeting" -DisplayName "room.plant.meeting" -OrganizationalUnit "OU=Resources,OU=Mississauga,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName room.plant.meeting@broan-nutone.ca
New-Mailbox -Room -Name "BNC-Room Reception Meeting Room" -DisplayName "BNC-Room Reception Meeting Room" -OrganizationalUnit "OU=Resources,OU=Mississauga,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Receptionmeetingroom@broan-nutone.ca
New-Mailbox -Room -Name "BNC-Room (Video Conf)" -DisplayName "BNC-Room (Video Conf)" -OrganizationalUnit "OU=Resources,OU=Mississauga,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName room.display.room@broan-nutone.ca
New-Mailbox -Room -Name "BNC-Room Finance Meeting Room" -DisplayName "BNC-Room Finance Meeting Room" -OrganizationalUnit "OU=Resources,OU=Mississauga,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName room.fin@broan-nutone.ca
New-Mailbox -Room -Name "AQH SurfaceHub" -DisplayName "AQH SurfaceHub" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName AQH.SurfaceHub@broan.com
New-Mailbox -Room -Name "HTF-BNC Conference Room_d83ea38917" -DisplayName "HTF-BNC Conference Room_d83ea38917" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName BNCConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-Broan Conference Room_1d453ed192" -DisplayName "HTF-Broan Conference Room_1d453ed192" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName BroanConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF4-Consumer Research" -DisplayName "HTF4-Consumer Research" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName HTF4ConsumerResearch@broan.com
New-Mailbox -Room -Name "HTF-ME Lab" -DisplayName "HTF-ME Lab" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName HTF-MELab@broan.com
New-Mailbox -Room -Name "HTF-Jensen Conference Room_102d397930" -DisplayName "HTF-Jensen Conference Room_102d397930" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName JensenConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-Lunch Room Annex_cfc7e4518b" -DisplayName "HTF-Lunch Room Annex_cfc7e4518b" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName LunchRoomAnnex@broan.com
New-Mailbox -Room -Name "HTF-NuTone Conference Room_210783b00e" -DisplayName "HTF-NuTone Conference Room_210783b00e" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName NutoneConferenceRoom@broan.com
New-Mailbox -Room -Name "BBPM-3 de Marzo Sala" -DisplayName "BBPM-3 de Marzo Sala" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName 3deMarzoSala@broan.com
New-Mailbox -Room -Name "HTF-Aubrey Conference Room" -DisplayName "HTF-Aubrey Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName AubreyConferenceRoom@broan.com
New-Mailbox -Room -Name "BBPM-DFT Sala" -DisplayName "BBPM-DFT Sala" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName DFTSala@broan.com
New-Mailbox -Room -Name "HTF-Engineering Conference Room" -DisplayName "HTF-Engineering Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName EngineeringConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-Executive Conference Room" -DisplayName "HTF-Executive Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName ExecutiveConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-Auto Hood Conference Room" -DisplayName "HTF-Auto Hood Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName HTF-AutoHoodConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-Best Training Center" -DisplayName "HTF-Best Training Center" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName HTF-BestTrainingCenter@broan.com
New-Mailbox -Room -Name "HTF-MKTG Conference Room" -DisplayName "HTF-MKTG Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName HTF-MKTG.ConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-NPD Conference Room" -DisplayName "HTF-NPD Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName HTF-NPDConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-Production Conference Room" -DisplayName "HTF-Production Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName HTF-ProductionConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-Kaizen Conference Room" -DisplayName "HTF-Kaizen Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName KaizenConferenceRoom@broan.com
New-Mailbox -Room -Name "BBPM-Mexico Sala" -DisplayName "BBPM-Mexico Sala" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName mexicosla@broan.com
New-Mailbox -Room -Name "HTF4-#1 Conference Room" -DisplayName "HTF4-#1 Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Plant4ConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF4-#6 Training Room" -DisplayName "HTF4-#6 Training Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Plant4TrainingRoom@broan.com
New-Mailbox -Room -Name "HTF-Rangaire Conference Room" -DisplayName "HTF-Rangaire Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName RangaireConferenceRoom@broan.com
New-Mailbox -Room -Name "HTF-Zephyr Conference Room" -DisplayName "HTF-Zephyr Conference Room" -OrganizationalUnit "OU=Resources,OU=Hartford,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName ZephyrConferenceRoom@broan.com
New-Mailbox -Room -Name "VEN-Salle Albert Einstein" -DisplayName "VEN-Salle Albert Einstein" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.albert.heinste@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Galillee" -DisplayName "VEN-Salle Galillee" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.galillee@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Jean Coupal" -DisplayName "VEN-Salle Jean Coupal" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.jean.coupal@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Leonard de Vinci" -DisplayName "VEN-Salle Leonard de Vinci" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.leonard.devinc@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Marie Curie" -DisplayName "VEN-Salle Marie Curie" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.marie.curie@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Martin Luther King" -DisplayName "VEN-Salle Martin Luther King" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.martin.luther@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Steve-Jobs (Acad?mie)_9555cbea72" -DisplayName "VEN-Salle Steve-Jobs (Acad?mie)_9555cbea72" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.stevejobs@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Innergy Conf" -DisplayName "VEN-Salle Innergy Conf" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName innergy.conf@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Pablo Picasso" -DisplayName "VEN-Salle Pablo Picasso" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.pablo.picasso@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Pascal-Ialenti (Video Conf)" -DisplayName "VEN-Salle Pascal-Ialenti (Video Conf)" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName salle.pascal.ialenti@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Centre d'excellence" -DisplayName "VEN-Salle Centre d'excellence" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Salle-Centredexcellence@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Creativite" -DisplayName "VEN-Salle Creativite" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Salle-Creativite@venmar.ca
New-Mailbox -Room -Name "VEN-Salle Innovation" -DisplayName "VEN-Salle Innovation" -OrganizationalUnit "OU=Resources,OU=Drummondville,OU=SITES,OU=BROAN,DC=broan,DC=com" -UserprincipalName Salle-Innovation@venmar.ca