new-mailbox -room -PrimarySmtpAddress BESTSPA-Room4@broan.onmicrosoft.com -Name "BSRM04" -DisplayName "BSRM04"
new-mailbox -room -PrimarySmtpAddress BESTSPA-Room6@broan.onmicrosoft.com -Name "BSRM06" -DisplayName "BSRM06"
new-mailbox -room -PrimarySmtpAddress BESTSPA-Room5@broan.onmicrosoft.com -Name "BEST SPA - Room 5" -DisplayName "BEST SPA - Room 5"
new-mailbox -room -PrimarySmtpAddress Cirrus@broan.onmicrosoft.com -Name "BEST SPA - Cirrus" -DisplayName "BEST SPA - Cirrus"
new-mailbox -room -PrimarySmtpAddress Dado@broan.onmicrosoft.com -Name "BEST SPA - Dado" -DisplayName "BEST SPA - Dado"
new-mailbox -room -PrimarySmtpAddress Ghost@broan.onmicrosoft.com -Name "BEST SPA - Ghost" -DisplayName "BEST SPA - Ghost"
new-mailbox -room -PrimarySmtpAddress Mars@broan.onmicrosoft.com -Name "BEST SPA - Mars" -DisplayName "BEST SPA - Mars"
new-mailbox -room -PrimarySmtpAddress Moon@broan.onmicrosoft.com -Name "BEST SPA - Moon" -DisplayName "BEST SPA - Moon"
new-mailbox -room -PrimarySmtpAddress Saturn@broan.onmicrosoft.com -Name "BEST SPA - Saturn" -DisplayName "BEST SPA - Saturn"
new-mailbox -room -PrimarySmtpAddress Showroom@broan.onmicrosoft.com -Name "BEST SPA - Showroom" -DisplayName "BEST SPA - Showroom"
new-mailbox -room -PrimarySmtpAddress Smooth@broan.onmicrosoft.com -Name "BEST SPA - Smooth" -DisplayName "BEST SPA - Smooth"
new-mailbox -room -PrimarySmtpAddress Venus@broan.onmicrosoft.com -Name "BEST SPA - Venus" -DisplayName "BEST SPA - Venus"
new-mailbox -room -PrimarySmtpAddress Vertigo@broan.onmicrosoft.com -Name "BEST SPA - Vertigo" -DisplayName "BEST SPA - Vertigo"
new-mailbox -room -PrimarySmtpAddress HFTTRT@broan.onmicrosoft.com -Name "HTF-Boardroom" -DisplayName "HTF-Boardroom"
new-mailbox -room -PrimarySmtpAddress room.plant.meeting@broan.onmicrosoft.com -Name "room.plant.meeting" -DisplayName "room.plant.meeting"
new-mailbox -room -PrimarySmtpAddress Receptionmeetingroom@broan.onmicrosoft.com -Name "BNC-Room Reception Meeting Room" -DisplayName "BNC-Room Reception Meeting Room"
new-mailbox -room -PrimarySmtpAddress room.display.room@broan.onmicrosoft.com -Name "BNC-Room (Video Conf)" -DisplayName "BNC-Room (Video Conf)"
new-mailbox -room -PrimarySmtpAddress room.fin@broan.onmicrosoft.com -Name "BNC-Room Finance Meeting Room" -DisplayName "BNC-Room Finance Meeting Room"
new-mailbox -room -PrimarySmtpAddress AQH.SurfaceHub@broan.onmicrosoft.com -Name "AQH SurfaceHub" -DisplayName "AQH SurfaceHub"
new-mailbox -room -PrimarySmtpAddress BNCConferenceRoom@broan.onmicrosoft.com -Name "HTF-BNC Conference Room_d83ea38917" -DisplayName "HTF-BNC Conference Room_d83ea38917"
new-mailbox -room -PrimarySmtpAddress BroanConferenceRoom@broan.onmicrosoft.com -Name "HTF-Broan Conference Room_1d453ed192" -DisplayName "HTF-Broan Conference Room_1d453ed192"
new-mailbox -room -PrimarySmtpAddress HTF4ConsumerResearch@broan.onmicrosoft.com -Name "HTF4-Consumer Research" -DisplayName "HTF4-Consumer Research"
new-mailbox -room -PrimarySmtpAddress HTF-MELab@broan.onmicrosoft.com -Name "HTF-ME Lab" -DisplayName "HTF-ME Lab"
new-mailbox -room -PrimarySmtpAddress JensenConferenceRoom@broan.onmicrosoft.com -Name "HTF-Jensen Conference Room_102d397930" -DisplayName "HTF-Jensen Conference Room_102d397930"
new-mailbox -room -PrimarySmtpAddress LunchRoomAnnex@broan.onmicrosoft.com -Name "HTF-Lunch Room Annex_cfc7e4518b" -DisplayName "HTF-Lunch Room Annex_cfc7e4518b"
new-mailbox -room -PrimarySmtpAddress NutoneConferenceRoom@broan.onmicrosoft.com -Name "HTF-NuTone Conference Room_210783b00e" -DisplayName "HTF-NuTone Conference Room_210783b00e"
new-mailbox -room -PrimarySmtpAddress 3deMarzoSala@broan.onmicrosoft.com -Name "BBPM-3 de Marzo Sala" -DisplayName "BBPM-3 de Marzo Sala"
new-mailbox -room -PrimarySmtpAddress AubreyConferenceRoom@broan.onmicrosoft.com -Name "HTF-Aubrey Conference Room" -DisplayName "HTF-Aubrey Conference Room"
new-mailbox -room -PrimarySmtpAddress DFTSala@broan.onmicrosoft.com -Name "BBPM-DFT Sala" -DisplayName "BBPM-DFT Sala"
new-mailbox -room -PrimarySmtpAddress EngineeringConferenceRoom@broan.onmicrosoft.com -Name "HTF-Engineering Conference Room" -DisplayName "HTF-Engineering Conference Room"
new-mailbox -room -PrimarySmtpAddress ExecutiveConferenceRoom@broan.onmicrosoft.com -Name "HTF-Executive Conference Room" -DisplayName "HTF-Executive Conference Room"
new-mailbox -room -PrimarySmtpAddress HTF-AutoHoodConferenceRoom@broan.onmicrosoft.com -Name "HTF-Auto Hood Conference Room" -DisplayName "HTF-Auto Hood Conference Room"
new-mailbox -room -PrimarySmtpAddress HTF-BestTrainingCenter@broan.onmicrosoft.com -Name "HTF-Best Training Center" -DisplayName "HTF-Best Training Center"
new-mailbox -room -PrimarySmtpAddress HTF-MKTG.ConferenceRoom@broan.onmicrosoft.com -Name "HTF-MKTG Conference Room" -DisplayName "HTF-MKTG Conference Room"
new-mailbox -room -PrimarySmtpAddress HTF-NPDConferenceRoom@broan.onmicrosoft.com -Name "HTF-NPD Conference Room" -DisplayName "HTF-NPD Conference Room"
new-mailbox -room -PrimarySmtpAddress HTF-ProductionConferenceRoom@broan.onmicrosoft.com -Name "HTF-Production Conference Room" -DisplayName "HTF-Production Conference Room"
new-mailbox -room -PrimarySmtpAddress KaizenConferenceRoom@broan.onmicrosoft.com -Name "HTF-Kaizen Conference Room" -DisplayName "HTF-Kaizen Conference Room"
new-mailbox -room -PrimarySmtpAddress mexicosla@broan.onmicrosoft.com -Name "BBPM-Mexico Sala" -DisplayName "BBPM-Mexico Sala"
new-mailbox -room -PrimarySmtpAddress Plant4ConferenceRoom@broan.onmicrosoft.com -Name "HTF4-#1 Conference Room" -DisplayName "HTF4-#1 Conference Room"
new-mailbox -room -PrimarySmtpAddress Plant4TrainingRoom@broan.onmicrosoft.com -Name "HTF4-#6 Training Room" -DisplayName "HTF4-#6 Training Room"
new-mailbox -room -PrimarySmtpAddress RangaireConferenceRoom@broan.onmicrosoft.com -Name "HTF-Rangaire Conference Room" -DisplayName "HTF-Rangaire Conference Room"
new-mailbox -room -PrimarySmtpAddress ZephyrConferenceRoom@broan.onmicrosoft.com -Name "HTF-Zephyr Conference Room" -DisplayName "HTF-Zephyr Conference Room"
new-mailbox -room -PrimarySmtpAddress salle.albert.heinste@broan.onmicrosoft.com -Name "VEN-Salle Albert Einstein" -DisplayName "VEN-Salle Albert Einstein"
new-mailbox -room -PrimarySmtpAddress salle.galillee@broan.onmicrosoft.com -Name "VEN-Salle Galillee" -DisplayName "VEN-Salle Galillee"
new-mailbox -room -PrimarySmtpAddress salle.jean.coupal@broan.onmicrosoft.com -Name "VEN-Salle Jean Coupal" -DisplayName "VEN-Salle Jean Coupal"
new-mailbox -room -PrimarySmtpAddress salle.leonard.devinc@broan.onmicrosoft.com -Name "VEN-Salle Leonard de Vinci" -DisplayName "VEN-Salle Leonard de Vinci"
new-mailbox -room -PrimarySmtpAddress salle.marie.curie@broan.onmicrosoft.com -Name "VEN-Salle Marie Curie" -DisplayName "VEN-Salle Marie Curie"
new-mailbox -room -PrimarySmtpAddress salle.martin.luther@broan.onmicrosoft.com -Name "VEN-Salle Martin Luther King" -DisplayName "VEN-Salle Martin Luther King"
new-mailbox -room -PrimarySmtpAddress salle.stevejobs@broan.onmicrosoft.com -Name "VEN-Salle Steve-Jobs (Acad?mie)_9555cbea72" -DisplayName "VEN-Salle Steve-Jobs (Acad?mie)_9555cbea72"
new-mailbox -room -PrimarySmtpAddress innergy.conf@broan.onmicrosoft.com -Name "VEN-Salle Innergy Conf" -DisplayName "VEN-Salle Innergy Conf"
new-mailbox -room -PrimarySmtpAddress salle.pablo.picasso@broan.onmicrosoft.com -Name "VEN-Salle Pablo Picasso" -DisplayName "VEN-Salle Pablo Picasso"
new-mailbox -room -PrimarySmtpAddress salle.pascal.ialenti@broan.onmicrosoft.com -Name "VEN-Salle Pascal-Ialenti (Video Conf)" -DisplayName "VEN-Salle Pascal-Ialenti (Video Conf)"
new-mailbox -room -PrimarySmtpAddress Salle-Centredexcellence@broan.onmicrosoft.com -Name "VEN-Salle Centre d'excellence" -DisplayName "VEN-Salle Centre d'excellence"
new-mailbox -room -PrimarySmtpAddress Salle-Creativite@broan.onmicrosoft.com -Name "VEN-Salle Creativite" -DisplayName "VEN-Salle Creativite"
new-mailbox -room -PrimarySmtpAddress Salle-Innovation@broan.onmicrosoft.com -Name "VEN-Salle Innovation" -DisplayName "VEN-Salle Innovation"